spring:
#  redis:
#    cluster:
#      nodes:
#      - 47.94.158.36:7011
#      - 47.94.158.36:7012
#      - 47.94.158.36:7013
#      - 47.94.158.36:7014
#      - 47.94.158.36:7015
#      - 47.94.158.36:7016
#    password: zxcv@redis
#    max-redirects: 3  # 获取失败 最大重定向次数
#    #连接超时时间（毫秒）
#    timeout: 10000
#    lettuce:
#      max-active: 500
#      max-idle: 1000
#      min-idle: 100
#      max-wait: -1
  redis:
    host: 182.92.118.137
    database: 0
    port: 6379
    password: zxcv@redis
    #连接超时时间（毫秒）
    timeout: 10000
    lettuce:
      pool:
        max-wait: -1ms





  application:
    name: zxcv-web
  springdubbo:
    application:
      name: ${spring.application.name}
    registry:
      address: zookeeper://127.0.0.1:2181
      #address: zookeeper://47.104.196.152:2181
    provider:
      version: 1.0.0


logging:
  level:
    org.springframework.web: error
    io.lettuce.core.protocol: error
  path: ../zxcv-logs/${spring.application.name} #日志目录-当前根目录的外一级
  file: ${logging.path}/${spring.application.name}.log
  config: classpath:logback-spring.xml



server:
  port: 8088
#  servlet:
#    context-path: /prod-api


rocketmq:
  nameServer: 47.104.138.10:9876
  producer:
    group: clouds_park
    sendMessageTimeout: 300000
    
fdfs:
  fdsurl: http://47.94.158.36:8080 #fds访问url
  soTimeout: 1500
  connectTimeout: 600
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
    - 47.94.158.36:22122