spring:
  redis:
      host:  47.94.158.36
      database: 0
      port: 7013
      password: zxcv@redis
      #连接超时时间（毫秒）
      timeout: 10000
      lettuce:
        pool:
          max-wait: -1ms





  application:
    name: zxcv-web
  springdubbo:
    application:
      name: ${spring.application.name}
    registry:
      address: zookeeper://127.0.0.1:2181
      #address: zookeeper://47.104.196.152:2181
    provider:
      version: 1.0.0


logging:
  level:
    org.springframework.web: error
    io.lettuce.core.protocol: error
  path:  ./logs/${spring.application.name}
  file: ${logging.path}/${spring.application.name}.log
  config: classpath:logback-spring.xml



server:
  port: 8088
#  servlet:
#    context-path: /prod-api


rocketmq:
  nameServer: 47.104.138.10:9876
  producer:
    group: clouds_park
    sendMessageTimeout: 300000
    
fdfs:
  fdsurl: http://47.94.158.36:8080 #fds访问url
  soTimeout: 1500
  connectTimeout: 600
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
    - 47.94.158.36:22122